#!/bin/sh

#ergo-dep -af bootstrap

SEP=none
BADSEP=""

for sep in " " , "#" + - = 0; do
  if (IFS= ;echo "$*") | grep -vq "$sep"; then
    SEP=$sep
    break
  else
    BADSEP=$BADSEP$sep
  fi
done

if [ "$SEP" = "none" ]; then
  echo "Couldn't find a separator in \"$BADSEP\" for args"
  exit 1
fi

${ERL_CALL} -a "ergo_cli tasks [\"${ERGO_WORKSPACE}\", \"${ERGO_TASK_ID}\", \"${0}\", \"${sep}\", \"$(IFS=$sep;echo "${*}")\"]" -name ${ERGO_NODE}
echo
