#!/usr/bin/env bash

set -ex

scripts/ergo-filefrom rosters/eunit_names.txt tasks/eunit-roster
MODULE_NAMES=$(< rosters/eunit_names.txt)

for f in $MODULE_NAMES; do
  scripts/filefrom log/results/eunit/$f tasks/run-eunit-test $f
done

FAILS=""
for f in $MODULE_NAMES; do
  logfile=log/results/eunit/$f
  test -f $logfile
  if tail -n 1 $logfile | grep -q failed; then
    FAILS="$FAILS $logfile"
  fi
done

if [ ! -z "${FAILS}" ]; then
  echo "Failing eunit logs: " $FAILS
  for f in $FAILS; do
    cat $f
  done
  exit 1
fi
