#!/usr/bin/env bash
set -ex

PROJECT=$(basename $(pwd))
SOURCE=src/${PROJECT}.app.src
TARGET=ebin/${PROJECT}.app

ergo-taskfile --requires $SOURCE
ergo-taskfile --produces $TARGET

ergo-dep -af tasks/requires-all-compiled $0 "$@"
ergo-taskfile --requires rosters/names.txt

MODULES=$(cat rosters/names.txt | sed 's/.*/'\0',/' | tr -d '\n')

grep -Eq '^[^%]*{modules,' $SOURCE #Need an empty modules entry in src/PROJECT.app.src

sed "s/{modules,[[:space:]]*\[\]}/{modules, \[${MODULES}\]}/" < $SOURCE > $TARGET
