#!/usr/bin/env bash
set -ex

env | grep 'ERGO'
if [ $# -lt 1 ]; then
  ergo-task-invalid "$0 needs arg 1 (a source suite)"
  exit 1
fi

SOURCE_SUITE=${1:?$(ergo-task-invalid "$0 needs arg 1 (a source suite)")}
SOURCE=test/${SOURCE_SUITE}_SUITE.erl

TARGET=test/${SOURCE_SUITE}_SUITE.beam
#The old makefile dep'd on 'build-ct-deps' which appears to be user config'd
ergo-taskfile --produces $TARGET

HEADERS=$(erlc -M -MP -MG ${SOURCE} | grep ':$' | grep -v '^/' | sed 's/:$//')
for h in $HEADERS; do
  ergo-taskfile --requires $h
done

TEST_ERLC_OPTS="+debug_info +warn_export_vars +warn_shadow_vars +warn_obsolete_guard -DTEST=1 -DEXTRA=1" # +'{parse_transform, eunit_autoexport}'"
erlc -v ${TEST_ERLC_OPTS} -o test/ $SOURCE -pa ebin/
