#!/usr/bin/env bash
set -ex

NAME=${1:?No name specified to erlc}

ERLC_OPTS="-Werror +debug_info +warn_export_all +warn_export_vars +warn_shadow_vars +warn_obsolete_guard" # +bin_opt_info +warn_missing_spec"

src="src/${NAME}.erl"
beam="ebin/${NAME}.beam"

ergo-taskfile --requires $src
ergo-taskfile --produces $beam

HEADERS=$(erlc -M -MP -MG $src | grep ':$' | grep -v '^/' | sed 's/:$//')
for h in $HEADERS; do
  ergo-taskfile --requires $h
done

erlc -v $(ERLC_OPTS) -o ebin/ \ -pa ebin/ -I include/ $src
