#!/usr/bin/env bash
set -ex

suite_roster=rosters/suite_names.txt
ergo-taskfile --produces $suite_roster

mkdir -p $(dirname $suite_roster)
find test/ -type f -name \*_SUITE.erl -exec basename {} \; | sed 's/_SUITE.erl//' | sort > $suite_roster
