#!releases/ergo-0.1.0/bin/escript
%%! -boot releases/ergo-0.1.0/bin/ergo

main(Args) ->
    process_flag(trap_exit, true),
    Taskname = [list_to_binary(Part) || Part <- Args],
    io:format("Starting build~n", []),
    {ok, WS, _WatchRef} = ergo:attach_workspace(),
    {ok, {build_id, Id}} = ergo:run_build(WS, [{task, Taskname}]),

    {ok, Success, Message} = ergo_api:wait_on_build(WS, Id),
    timer:sleep(500), % XXX really, should have some way to flush events
    io:format("Build ~.10b : ~p completed.~n  ~p - ~p~n", [Id, Args, Success, Message]).
