#!/usr/bin/env bash

if [ $# -lt 1 ]; then
  ergo-task-invalid "Called $0 without the name of a task"
fi
TASK=$(realpath ${@} | sed "s#^${ERGO_WORKSPACE}\(\/\)\?##")

if echo $TASK | grep '^/'; then
  ergo-task-invalid "Must use actual taskname (i.e. project rooted) not: ${TASK}"
fi

scripts/filefrom rosters/beam.txt tasks/beam-chains
for beam in $(< rosters/beam.txt); do
  ergo-taskfile --requires $beam --task $TASK
done
